-- =====================================================================
-- تتبّع زوار موقع "طالب علم" — شغّل الملف ده مرة واحدة بس
-- في Supabase Dashboard → SQL Editor → New query → الصق والصق Run
-- =====================================================================

-- 1) جدول الأحداث
create table if not exists site_events (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  visitor_id   text not null,
  event_type   text not null check (event_type in (
                 'page_view', 'reached_download', 'download_clicked', 'whatsapp_followed'
               )),
  page         text,
  referrer     text,
  user_agent   text
);

create index if not exists site_events_event_type_idx on site_events (event_type);
create index if not exists site_events_visitor_id_idx on site_events (visitor_id);
create index if not exists site_events_created_at_idx on site_events (created_at);

-- 2) تأمين الجدول: أي حد معاه مفتاح anon (اللي هيتحط في كود الموقع، وهو ظاهر
--    لأي حد يفتح الموقع) يقدر بس "يسجّل" حدث جديد، ومينفعش يقرا أي بيانات.
alter table site_events enable row level security;

drop policy if exists "allow insert from anyone" on site_events;
create policy "allow insert from anyone"
  on site_events for insert
  to anon
  with check (true);

-- ملحوظة: مفيش أي policy لقراءة الجدول، يعني حتى لو حد فتح مفتاح الـ anon
-- من كود الموقع مش هيقدر يقرا بيانات الزوار خالص.

-- 3) دالة خاصة لجلب الإحصائيات — محمية بكلمة سر تتحط هنا في الكود
--    (غيّرها لأي حاجة تانية غير اللي مكتوبة، وده هو "الباسورد" بتاع صفحة الإحصائيات)
create or replace function get_site_stats(p_password text)
returns table (
  total_page_views          bigint,
  unique_visitors           bigint,
  total_reached_download    bigint,
  unique_reached_download   bigint,
  total_downloaded          bigint,
  unique_downloaded         bigint,
  total_whatsapp_followed   bigint,
  unique_whatsapp_followed  bigint,
  reached_but_not_downloaded bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_password is distinct from '@moaz@' then
    raise exception 'unauthorized';
  end if;

  return query
  select
    (select count(*) from site_events where event_type = 'page_view'),
    (select count(distinct visitor_id) from site_events where event_type = 'page_view'),
    (select count(*) from site_events where event_type = 'reached_download'),
    (select count(distinct visitor_id) from site_events where event_type = 'reached_download'),
    (select count(*) from site_events where event_type = 'download_clicked'),
    (select count(distinct visitor_id) from site_events where event_type = 'download_clicked'),
    (select count(*) from site_events where event_type = 'whatsapp_followed'),
    (select count(distinct visitor_id) from site_events where event_type = 'whatsapp_followed'),
    (select count(distinct visitor_id) from site_events
       where event_type = 'reached_download'
       and visitor_id not in (select visitor_id from site_events where event_type = 'download_clicked'));
end;
$$;

-- 4) دالة تانية لجدول يومي (آخر 14 يوم) — تظهر في صفحة الإحصائيات كجدول بسيط
create or replace function get_site_stats_daily(p_password text)
returns table (
  day                 date,
  page_views          bigint,
  reached_download    bigint,
  downloaded          bigint,
  whatsapp_followed   bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_password is distinct from '@moaz@' then
    raise exception 'unauthorized';
  end if;

  return query
  select
    d::date as day,
    count(*) filter (where e.event_type = 'page_view'),
    count(*) filter (where e.event_type = 'reached_download'),
    count(*) filter (where e.event_type = 'download_clicked'),
    count(*) filter (where e.event_type = 'whatsapp_followed')
  from generate_series(current_date - interval '13 days', current_date, interval '1 day') d
  left join site_events e on e.created_at::date = d::date
  group by d
  order by d asc;
end;
$$;

-- السماح لمفتاح anon باستدعاء الدالتين بس (مش بقراءة الجدول مباشرة)
grant execute on function get_site_stats(text) to anon;
grant execute on function get_site_stats_daily(text) to anon;
